import React from "react";
import {
  Flame,
  Coffee,
  IceCream2,
  Egg,
  Pizza,
  Beef,
  Fish,
  Salad,
  Soup,
  Sandwich,
  Cookie,
  Cake,
  Apple,
  Carrot,
  Grape,
  UtensilsCrossed,
  Wine,
  Beer,
  Milk,
  Star,
  Sun,
  Moon,
  Leaf,
  Zap,
  Drumstick,
  ShoppingBag,
  Croissant,
  CupSoda,
  Candy,
  ChefHat,
} from "lucide-react";

export const renderCategoryIcon = (icon: string, size = 20) => {
  const map: Record<string, React.ReactNode> = {
    flame: <Flame size={size} />,
    drumstick: <Drumstick size={size} />,
    beef: <Beef size={size} />,
    fish: <Fish size={size} />,
    egg: <Egg size={size} />,
    soup: <Soup size={size} />,
    salad: <Salad size={size} />,
    pizza: <Pizza size={size} />,
    sandwich: <Sandwich size={size} />,
    croissant: <Croissant size={size} />,
    "chef-hat": <ChefHat size={size} />,
    "utensils-crossed": <UtensilsCrossed size={size} />,
    coffee: <Coffee size={size} />,
    "cup-soda": <CupSoda size={size} />,
    beer: <Beer size={size} />,
    wine: <Wine size={size} />,
    milk: <Milk size={size} />,
    "ice-cream": <IceCream2 size={size} />,
    cake: <Cake size={size} />,
    cookie: <Cookie size={size} />,
    candy: <Candy size={size} />,
    apple: <Apple size={size} />,
    carrot: <Carrot size={size} />,
    grape: <Grape size={size} />,
    leaf: <Leaf size={size} />,
    "shopping-bag": <ShoppingBag size={size} />,
    star: <Star size={size} />,
    sun: <Sun size={size} />,
    moon: <Moon size={size} />,
    zap: <Zap size={size} />,
  };
  return map[icon] ?? <UtensilsCrossed size={size} />;
};
